services:
  db:
    image: postgres:17
    container_name: healthion-api-postgres
    environment:
      POSTGRES_DB: healthion
      POSTGRES_USER: healthion
      POSTGRES_PASSWORD: healthion
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["./prestart.sh"]
    command: ["scripts/start/app.sh"]
    container_name: healthion-api-app
    env_file:
      - ./envs/.env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - BACKEND_CORS_ALLOW_ALL=true
      - OPEN_WEARABLES_API_URL=http://host.docker.internal:8000
    dns:
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8001:8000"
    depends_on:
      - db
    volumes:
      - .:/root_project
      - /root_project/.venv
      - type: bind
        source: ./envs/.env
        target: /root_project/envs/.env
        bind:
          create_host_path: false
    restart: on-failure

volumes:
  postgres_data:
